[package]
name = "solana_node"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full", "process"] }
solana-sdk = "2.2.1"
solana-client = "2.2.3"
log = "0.4"
env_logger = "0.11"